application: james-squires
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: blog/stylesheets
  
- url: /javascripts
  static_dir: blog/javascripts  
    
- url: /.*
  script: main.py
  

